<?php
declare(strict_types=1);

// Dedline SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

DedlineUtility::setRegistrar(function (DedlineUtility $u): void {
    $u->clean = [DedlineClean::class, 'call'];
    $u->done = [DedlineDone::class, 'call'];
    $u->make_error = [DedlineMakeError::class, 'call'];
    $u->feature_add = [DedlineFeatureAdd::class, 'call'];
    $u->feature_hook = [DedlineFeatureHook::class, 'call'];
    $u->feature_init = [DedlineFeatureInit::class, 'call'];
    $u->fetcher = [DedlineFetcher::class, 'call'];
    $u->make_fetch_def = [DedlineMakeFetchDef::class, 'call'];
    $u->make_context = [DedlineMakeContext::class, 'call'];
    $u->make_options = [DedlineMakeOptions::class, 'call'];
    $u->make_request = [DedlineMakeRequest::class, 'call'];
    $u->make_response = [DedlineMakeResponse::class, 'call'];
    $u->make_result = [DedlineMakeResult::class, 'call'];
    $u->make_point = [DedlineMakePoint::class, 'call'];
    $u->make_spec = [DedlineMakeSpec::class, 'call'];
    $u->make_url = [DedlineMakeUrl::class, 'call'];
    $u->param = [DedlineParam::class, 'call'];
    $u->prepare_auth = [DedlinePrepareAuth::class, 'call'];
    $u->prepare_body = [DedlinePrepareBody::class, 'call'];
    $u->prepare_headers = [DedlinePrepareHeaders::class, 'call'];
    $u->prepare_method = [DedlinePrepareMethod::class, 'call'];
    $u->prepare_params = [DedlinePrepareParams::class, 'call'];
    $u->prepare_path = [DedlinePreparePath::class, 'call'];
    $u->prepare_query = [DedlinePrepareQuery::class, 'call'];
    $u->graphql_body = [DedlineGraphql::class, 'body'];
    $u->graphql_errors = [DedlineGraphql::class, 'errors'];
    $u->result_basic = [DedlineResultBasic::class, 'call'];
    $u->result_body = [DedlineResultBody::class, 'call'];
    $u->result_headers = [DedlineResultHeaders::class, 'call'];
    $u->transform_request = [DedlineTransformRequest::class, 'call'];
    $u->transform_response = [DedlineTransformResponse::class, 'call'];
});
